@eAppointmentServer.WebAPI_HostAddress = http://localhost:5255

POST http://localhost:5255/api/Auth/Login
Accept: application/json
Content-Type: application/json

{
    "userNameOrEmail": "string",
    "password": "string"
}

###
